VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = 'mutlitier-db-berkshelf'
#  config.vm.box = 'centos_7'
  config.vm.box = 'opscode-ubuntu-14.04'
  config.vm.network "public_network"

  # config.vm.provider "virtualbox" do |v|
  #   v.memory = 1624
  #   v.cpus = 2
  # end
  #config.berkshelf.enabled = true
  #config.vm.network :forwarded_port, guest: 8081, host: 8481
  config.vm.network :forwarded_port, guest: 80, host: 8880
  config.vm.network :forwarded_port, guest: 8080, host: 8180 

  config.vm.provision "chef_client" do |chef|
    chef.chef_server_url = "https://api.opscode.com/organizations/cat1"
    chef.validation_key_path = "/home/sraddhananad/chef_workspace/chef_cat1/.chef/cat1-validator.pem"
    chef.validation_client_name = "cat1-validator"
    chef.client_key_path = "/home/sraddhananad/chef_workspace/chef_cat1/.chef/pcjoshi9.pem"
    chef.node_name ="pcjoshi9"
    chef.environment = "Dev"
    chef.run_list = [
      'recipe[nginx]',
      'recipe[loadblncr::default]'
    ]
  end

end
