---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: win2012-chef11
    driver_config:
      box: windows-2012r2
    provisioner:
      require_chef_omnibus: 11.16.4
  - name: win2012-chef12
    driver_config:
      box: windows-2012r2
    provisioner:
      require_chef_omnibus: latest

suites:
  - name: default
    run_list:
      - recipe[iis::default]

