---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 11.16.2

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[lamp_role::default]
      # Integration tests for php applications
      - recipe[lamp_role::_integration]
    attributes:
      apt:
        # Force apt to update package cache at compile time
        compile_time_update: true
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
