language: ruby
rvm:
- 2.1.0
bundler_args: --without integration
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
before_script:
  - bundle exec berks
script:
  - bundle exec foodcritic .
