
source "https://api.berkshelf.com"
metadata

cookbook 'app_data_handler', path: "../app_data_handler"
cookbook 'java8', path: "../java8"
cookbook 'unzip', path: "../unzip"
cookbook 'docker', path: "../docker"
cookbook 'git', path: "../git"
