VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = 'deploy-upgrade-catalyst-berkshelf'
  config.vm.box = 'ubuntu/trusty64'
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
 
  config.berkshelf.enabled = true
  config.vm.network :forwarded_port, guest: 3001, host: 3111, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
 
  config.vm.provision :chef_solo do |chef|
  chef.install = true
  chef.version = "12.6.0"

 chef.json = {
      rlcatalyst: {
        # nexusUrl: "http://nexus.rlcatalyst.com/nexus/content/repositories/catalyst/org/catalyst/D4D/3.02.100/D4D-3.02.100.zip",
        # version: '3.02.100',
        # applicationNodeIP: 'localhost'
        containerId: 'sradhu',
        containerPort: "8765",
        dockerRepo: 'relevancelab/mongodb'

        }
  }

    chef.run_list = [
      'recipe[deploy_upgrade_catalyst::container]'
    ]
  end
end
