VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = 'deploy-rlcatalyst-berkshelf'
  config.vm.box = 'ubuntu/trusty64'
  config.berkshelf.enabled = true
  config.vm.network "public_network"
  config.vm.network :forwarded_port, guest: 3001, host: 3101
    
  config.vm.provision :chef_solo do |chef|
    chef.install = true
    chef.version = "12.6.0"

    
    chef.run_list = [
      'recipe[git]',
      #'recipe[nodejs]',
      'recipe[mongodb3]',
      'recipe[deploy_rlcatalyst]'
    ]
  end
end
