source "https://supermarket.chef.io"



metadata

cookbook 'yum-epel', '~> 0.3'
cookbook 'runit', '~> 1.2'
cookbook 'ohai', '~> 2.0'
cookbook 'build-essential', '~> 2.0'
cookbook  'bluepill', '~> 2.3'
cookbook  'apt', '~> 2.2'