source "https://supermarket.chef.io"



metadata

cookbook 'homebrew', '>= 0.0.0'
cookbook 'apt', '>= 0.0.0'
cookbook 'ark', '>= 0.0.0'
cookbook 'build-essential', '>= 0.0.0'
cookbook 'yum-epel', '>= 0.0.0'