source "https://supermarket.chef.io"

metadata

cookbook 'multitier_war', path: "../multitier_war"
cookbook 'tomcat-all-rl', path: "../tomcat-all-rl"
cookbook 'app_data_handler', path: "../app_data_handler"


